name: Build and Release

on:
  push:
    tags:
      - 'v*' # 推送以v开头的标签时触发，例如 v1.0.0, v2.1-alpha
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build and Publish - ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-arm64

          - os: ubuntu-22.04
            rid: linux-x64
          - os: ubuntu-22.04-arm
            rid: linux-arm64

          - os: macos-latest
            rid: osx-x64
          - os: macos-latest
            rid: osx-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Project
        run: |
          dotnet publish ./BongoCat_Like.csproj -c Release -r ${{ matrix.rid }} -p:OutputPath=./publish/${{ matrix.rid }}

      - name: Prepare Artifacts (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd ./publish
          rm -rf ${{ matrix.rid }} || true
          rm -rf ${{ matrix.rid }}native || true
          if [ -d "${{ matrix.rid }}publish" ]; then
            mv ${{ matrix.rid }}publish BongoCat-Like.${{ matrix.rid }} || true
            if [ "${{ matrix.os }}" = "macos-latest" ]; then
              strip -S BongoCat-Like.${{ matrix.rid }}/BongoCat_Like || true
            else
              strip --strip-debug BongoCat-Like.${{ matrix.rid }}/BongoCat_Like || true
              chmod 755 ../Tools/upx/${{ matrix.rid }}/upx
              ../Tools/upx/${{ matrix.rid }}/upx --best -q BongoCat-Like.${{ matrix.rid }}/BongoCat_Like BongoCat-Like.${{ matrix.rid }}/*.so || true
            fi
          fi

      - name: Prepare Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd ./publish
          Remove-Item -Path ${{ matrix.rid }} -Recurse -Force -ErrorAction Ignore
          Remove-Item -Path ${{ matrix.rid }}native -Recurse -Force -ErrorAction Ignore
          if (Test-Path -Path "${{ matrix.rid }}publish") {
            Rename-Item -Path ${{ matrix.rid }}publish -NewName BongoCat-Like.${{ matrix.rid }}
            if ("${{ matrix.rid }}" -eq "win-x64") {
              ../Tools/upx/win-x64/upx.exe --best -q (Get-Item "./BongoCat-Like.${{ matrix.rid }}/*.exe", "./BongoCat-Like.${{ matrix.rid }}/*.dll"); exit 0
            }
          }

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BongoCat-Like.${{ matrix.rid }}
          path: publish

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./release-artifacts
          pattern: BongoCat-Like.*
          merge-multiple: true

      - name: Get Changelog
        id : get_desc
        run: |
          result=$(awk '/^# /{if (flag) exit; flag=1} flag && NF' changelog.md)
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ${{ steps.get_desc.outputs.release_body }}
              - [更多更新内容](https://github.com/WLongSAMA/BongoCatLike/blob/main/changelog.md)
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          files: |
            ./release-artifacts/BongoCat-Like*.zip
